AUREX_RELEASE="14.04"
UBUNTU_CODENAME="trusty"
AUREX_CODENAME="trusty"
UBUNTU_DEFMIRROR="http://archive.ubuntu.com/ubuntu/"
AUREX_DEFMIRROR="http://cloud.ausiasmarch.net/aurex/"
UBUNTU_DEFPARTNER="http://archive.canonical.com/ubuntu/"
UBUNTU_DEFEXTRAS="http://extras.ubuntu.com/ubuntu/"
