AUREX_RELEASE="16.04"
UBUNTU_CODENAME="xenial"
AUREX_CODENAME="xenial"
UBUNTU_DEFMIRROR="http://archive.ubuntu.com/ubuntu/"
AUREX_DEFMIRROR="http://cloud.ausiasmarch.net/aurex/"
UBUNTU_DEFPARTNER="http://archive.canonical.com/ubuntu/"
UBUNTU_DEFEXTRAS="http://extras.ubuntu.com/ubuntu/"
